name: Build

on:
  workflow_call:
    inputs:
      env_file_content:
        description: 'Content of the .env file'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Save .env file
        env:
          ENV_FILE_CONTENT: ${{ inputs.env_file_content }}
        shell: bash
        run: |
          echo "$ENV_FILE_CONTENT" > .env

      - name: Build the app
        run: make prod_build_bundle

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist
