name: CD

on:
  push:
    branches:
      - "master"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Save .env file
        env:
          ENV_FILE_CONTENT: ${{ vars.ENV_FILE_CONTENT }}
        shell: bash
        run: |
          echo "$ENV_FILE_CONTENT" > .env

      - name: Build the app
        run: make prod_build_bundle

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
